package com.draft.footy;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Constants MEASURED from real football — never hand-edited.
 *
 * <p>Loaded once from {@code calibration.properties} on the classpath, which is generated by the
 * offline pipeline in {@code analysis/calibration/}: a Dixon-Coles model fitted by maximum likelihood
 * to ~36,000 real top-5-league matches (2006/07–2025/26), then bridged onto FIFA squad ratings. If the
 * file is missing the previous hand-tuned values are used instead, so a clone without it still runs.
 *
 * <p>Deliberately plain {@code java.util.Properties} — {@code com.draft.footy} stays free of Spring and
 * Jackson, so the no-Maven path ({@code javac -d out … && java -cp out com.draft.footy.Demo}) keeps working.
 *
 * <p><b>The model these describe</b> — {@link MatchEngine#lambda} must implement exactly this, which is
 * what {@link #MODEL_FORM} guards:
 * <pre>
 *   lambda = BASE_GOALS * exp( (attackRating  - ATTACK_REF ) / SCALE_ATTACK
 *                            - (defenceRating - DEFENCE_REF) / SCALE_DEFENCE
 *                            + HOME_ADV_LOG   [home side only] )
 * </pre>
 *
 * <p><b>Two things worth knowing before changing anything:</b>
 * <ul>
 *   <li><b>Attack and defence have different sensitivities</b> (≈20.1 vs ≈26.6). Squad rating predicts
 *       attacking output far better than defensive solidity — defending depends more on organisation than
 *       on individual ratings. A single SCALE cannot express that, which is why there are two.</li>
 *   <li><b>These are conditional on {@link Xi}'s line weights.</b> The fit used {@code Xi.attackRating()}
 *       and {@code Xi.defenceRating()} exactly as they are today. Change those weights and the constants
 *       must be refitted — they describe that specific function, not squad quality in the abstract.</li>
 * </ul>
 *
 * @see GameBalance for the values that are deliberately CHOSEN rather than measured
 */
public final class Calibration {

    private Calibration() { }

    /** The lambda() form these constants were fitted for. Bump when the engine's model changes. */
    public static final String MODEL_FORM = "split-scale-v2";

    public static final double BASE_GOALS;     // lambda for an average side vs an average side
    public static final double SCALE_ATTACK;   // rating points per log-goal, attacking
    public static final double SCALE_DEFENCE;  // rating points per log-goal, defending
    public static final double ATTACK_REF;     // mean attackRating across the fitted pool
    public static final double DEFENCE_REF;    // mean defenceRating across the fitted pool
    public static final double HOME_ADV_LOG;   // home advantage, in LOG-GOALS, applied to the home rate only
    public static final double RHO;            // Dixon-Coles low-score correction
    public static final double FORM_SIGMA;     // measured season-to-season form spread, in rating points

    /** True when the fitted file was found; false means the hand-tuned fallbacks are in use. */
    public static final boolean FITTED;
    public static final String SOURCE;

    static {
        Properties p = new Properties();
        boolean loaded = false;
        try (InputStream in = Calibration.class.getResourceAsStream("/calibration.properties")) {
            if (in != null) { p.load(in); loaded = true; }
        } catch (IOException ignored) {
            // fall through to the hand-tuned defaults
        }
        FITTED = loaded;

        String form = p.getProperty("model.form");
        if (loaded && form != null && !MODEL_FORM.equals(form))
            throw new IllegalStateException(
                "calibration.properties was fitted for model.form=" + form + " but this engine implements "
              + MODEL_FORM + ". Loading them would silently produce wrong physics. Refit, or check out the "
              + "matching engine version.");

        // Fallbacks are the pre-calibration hand-tuned values, translated into the split-scale form.
        BASE_GOALS    = dbl(p, "base.goals", 1.15);
        SCALE_ATTACK  = dbl(p, "scale.attack", 16.5);
        SCALE_DEFENCE = dbl(p, "scale.defence", 16.5);
        ATTACK_REF    = dbl(p, "attack.reference", 0.0);
        DEFENCE_REF   = dbl(p, "defence.reference", 0.0);
        HOME_ADV_LOG  = dbl(p, "home.adv.loggoals", 3.95 / 16.5);
        RHO           = dbl(p, "rho", -0.11);
        FORM_SIGMA    = dbl(p, "form.sigma", 0.78);
        SOURCE = loaded
            ? p.getProperty("fitted.matches", "?") + " matches, fitted " + p.getProperty("fitted.at", "?")
            : "hand-tuned fallback (calibration.properties not on the classpath)";
    }

    private static double dbl(Properties p, String key, double fallback) {
        String v = p.getProperty(key);
        if (v == null) return fallback;
        try {
            return Double.parseDouble(v.trim());
        } catch (NumberFormatException e) {
            throw new IllegalStateException("calibration.properties: " + key + " is not a number: " + v, e);
        }
    }

    /** One-line summary for startup logs and the Demo header. */
    public static String summary() {
        return String.format(
            "Calibration[%s] baseGoals=%.4f scaleAtt=%.2f scaleDef=%.2f homeAdv=%.4f rho=%.4f formSigma=%.2f (%s)",
            MODEL_FORM, BASE_GOALS, SCALE_ATTACK, SCALE_DEFENCE, HOME_ADV_LOG, RHO, FORM_SIGMA, SOURCE);
    }
}
