package com.draft.footy;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * The acceptance test for the calibration: feed the engine a REAL league-season and see whether it
 * reproduces what actually happened.
 *
 * <p>Every other check is indirect. The Demo sweep says the curve is monotonic and the draw rate is
 * plausible, but it plays a synthetic XI against a synthetic pyramid, so it can't tell you the constants
 * are <i>right</i> — only that they're self-consistent. This takes the twenty real clubs of a real season,
 * fields each one's best XI, simulates the league, and compares to the table that actually happened.
 *
 * <pre>
 *   mvn -q compile &amp;&amp; java -cp target/classes com.draft.footy.HistoricalValidation
 * </pre>
 *
 * Needs {@code analysis/calibration/data/joined.csv} (generated by the calibration pipeline) for the real
 * points. Pass a different path as the first argument if it lives elsewhere.
 */
public final class HistoricalValidation {

    private HistoricalValidation() { }

    private static final int SIMS = 200;   // average over many seasons: one season is mostly noise

    /** Seasons to check — a spread of eras, leagues, and one famous outlier apiece. */
    private static final String[][] TARGETS = {
        {"Premier League", "2017/18"},   // Man City 100 pts
        {"Premier League", "2015/16"},   // Leicester
        {"Premier League", "2007/08"},   // Derby's 11
        {"La Liga",        "2011/12"},   // Real Madrid 100
        {"Serie A",        "2013/14"},   // Juventus 102
        {"Bundesliga",     "2012/13"},
        {"Ligue 1",        "2015/16"},
    };

    private record Real(String club, int points, int gf, int ga) { }

    public static void main(String[] args) throws IOException {
        Path joined = Path.of(args.length > 0 ? args[0] : "analysis/calibration/data/joined.csv");
        if (!Files.exists(joined)) {
            System.err.println("missing " + joined + "\nRun the calibration pipeline first "
                + "(analysis/calibration/join_clubs.py).");
            return;
        }

        System.out.println(Calibration.summary());
        System.out.printf("form sigma in play: %.2f  (measured %.2f x multiplier %.2f)%n%n",
            GameBalance.effectiveFormSigma(), Calibration.FORM_SIGMA, GameBalance.FORM_SIGMA_MULTIPLIER);

        Map<String, List<Real>> real = readReal(joined);
        List<ClubSeason> pool = TierReport.loadPool();

        double sumAbsErr = 0, sumCorr = 0;
        int leaguesDone = 0, teamsDone = 0;

        for (String[] t : TARGETS) {
            String key = t[0] + "|" + t[1];
            List<Real> table = real.get(key);
            if (table == null) { System.out.println("no results for " + key + " — skipped"); continue; }

            List<Xi> xis = new ArrayList<>();
            List<Real> matched = new ArrayList<>();
            for (Real r : table)
                pool.stream()
                    .filter(cs -> cs.season.equals(t[1]) && cs.league.equals(t[0])
                               && ClubSeason.normClub(cs.club).equals(ClubSeason.normClub(r.club())))
                    .findFirst()
                    .ifPresent(cs -> { xis.add(cs.optimalXi()); matched.add(r); });

            if (xis.size() < 16) { System.out.println("only " + xis.size() + " clubs for " + key + " — skipped"); continue; }

            double[] predicted = averagePoints(xis, SIMS);
            double[] actual = matched.stream().mapToDouble(Real::points).toArray();

            double mae = 0;
            for (int i = 0; i < predicted.length; i++) mae += Math.abs(predicted[i] - actual[i]);
            mae /= predicted.length;
            double corr = pearson(predicted, actual);

            System.out.printf("%-16s %s   %2d clubs   MAE %5.1f pts   corr %+.3f%n",
                t[0], t[1], xis.size(), mae, corr);

            Integer[] order = new Integer[xis.size()];
            for (int i = 0; i < order.length; i++) order[i] = i;
            java.util.Arrays.sort(order, Comparator.comparingDouble((Integer i) -> -actual[i]));
            for (int k = 0; k < Math.min(3, order.length); k++) {
                int i = order[k];
                System.out.printf("     %-26s actual %3.0f   sim %5.1f   (%+.1f)%n",
                    matched.get(i).club(), actual[i], predicted[i], predicted[i] - actual[i]);
            }
            int worst = order[order.length - 1];
            System.out.printf("     %-26s actual %3.0f   sim %5.1f   (%+.1f)%n%n",
                matched.get(worst).club(), actual[worst], predicted[worst], predicted[worst] - actual[worst]);

            spread(xis, actual, t[0] + " " + t[1]);
            sumAbsErr += mae; sumCorr += corr; leaguesDone++; teamsDone += xis.size();
        }

        if (leaguesDone == 0) return;
        System.out.printf("OVERALL across %d league-seasons (%d clubs): MAE %.1f pts, mean corr %+.3f%n",
            leaguesDone, teamsDone, sumAbsErr / leaguesDone, sumCorr / leaguesDone);
        System.out.println("""

            Reading this: MAE is how far the simulated points sit from what really happened, averaged
            over every club. Some of that gap is the model; a lot of it is that a single real season is
            itself one draw from a distribution — the same squad replayed would not repeat its points.
            Correlation is the sharper number: it asks whether the engine ranks the league correctly.""");
    }

    /**
     * Does a SINGLE simulated season have the same shape as a real one?
     *
     * <p>This is the test that actually calibrates FORM_SIGMA, and it asks a different question from
     * the MAE above. Averaging 200 seasons gives the conditional mean, which is <i>supposed</i> to be
     * compressed — a predictor explaining R² of the variance has √R² of the spread, always. But a player
     * plays ONE season, and that one season should look like a real table: a champion near 90, a bottom
     * club near 25. If the simulated spread is too narrow the game feels flat no matter how good the
     * rankings are.
     */
    private static void spread(List<Xi> teams, double[] actual, String label) {
        int n = teams.size();
        MatchEngine engine = new MatchEngine();
        List<List<int[]>> schedule = SeasonSimulator.schedule(n % 2 == 0 ? n : n + 1);
        double maxSum = 0, minSum = 0, sdSum = 0, drawSum = 0, goalSum = 0;
        int games = 0;

        for (int s = 0; s < SIMS; s++) {
            Random rng = new Random(7_777_777L * s + 3);
            double[] form = new double[n];
            for (int i = 0; i < n; i++) form[i] = rng.nextGaussian() * SeasonSimulator.FORM_SIGMA;
            int[] pts = new int[n];
            for (List<int[]> round : schedule)
                for (int[] fx : round) {
                    if (fx[0] >= n || fx[1] >= n) continue;
                    int[] sc = engine.fastScore(teams.get(fx[0]), teams.get(fx[1]), form[fx[0]], form[fx[1]], rng);
                    if (sc[0] > sc[1]) pts[fx[0]] += 3;
                    else if (sc[0] < sc[1]) pts[fx[1]] += 3;
                    else { pts[fx[0]]++; pts[fx[1]]++; drawSum++; }
                    goalSum += sc[0] + sc[1];
                    games++;
                }
            int mx = Integer.MIN_VALUE, mn = Integer.MAX_VALUE;
            double mean = 0;
            for (int p : pts) { mx = Math.max(mx, p); mn = Math.min(mn, p); mean += p; }
            mean /= n;
            double var = 0;
            for (int p : pts) var += (p - mean) * (p - mean);
            maxSum += mx; minSum += mn; sdSum += Math.sqrt(var / n);
        }

        double rMean = java.util.Arrays.stream(actual).average().orElse(0);
        double rVar = java.util.Arrays.stream(actual).map(v -> (v - rMean) * (v - rMean)).sum() / actual.length;
        System.out.printf("     shape: champion %5.1f (real %3.0f) | bottom %5.1f (real %3.0f) | "
                + "spread sd %4.1f (real %4.1f)%n",
            maxSum / SIMS, java.util.Arrays.stream(actual).max().orElse(0),
            minSum / SIMS, java.util.Arrays.stream(actual).min().orElse(0),
            sdSum / SIMS, Math.sqrt(rVar));
        System.out.printf("     match : draws %4.1f%% (real 25.5%%) | goals/game %4.2f (real 2.72)%n%n",
            100.0 * drawSum / games, (double) goalSum / games);
    }

    /** Mean points per team over {@code sims} simulated seasons of this exact league. */
    private static double[] averagePoints(List<Xi> teams, int sims) {
        int n = teams.size();
        double[] total = new double[n];
        MatchEngine engine = new MatchEngine();
        List<List<int[]>> schedule = SeasonSimulator.schedule(n % 2 == 0 ? n : n + 1);

        for (int s = 0; s < sims; s++) {
            Random rng = new Random(1_000_003L * s + 17);
            double[] form = new double[n];
            for (int i = 0; i < n; i++) form[i] = rng.nextGaussian() * SeasonSimulator.FORM_SIGMA;
            int[] pts = new int[n];
            for (List<int[]> round : schedule)
                for (int[] fx : round) {
                    if (fx[0] >= n || fx[1] >= n) continue;          // bye, if the league was odd-sized
                    int[] sc = engine.fastScore(teams.get(fx[0]), teams.get(fx[1]), form[fx[0]], form[fx[1]], rng);
                    if (sc[0] > sc[1]) pts[fx[0]] += 3;
                    else if (sc[0] < sc[1]) pts[fx[1]] += 3;
                    else { pts[fx[0]]++; pts[fx[1]]++; }
                }
            for (int i = 0; i < n; i++) total[i] += pts[i];
        }
        for (int i = 0; i < n; i++) total[i] /= sims;
        return total;
    }

    private static double pearson(double[] x, double[] y) {
        int n = x.length;
        double mx = 0, my = 0;
        for (int i = 0; i < n; i++) { mx += x[i]; my += y[i]; }
        mx /= n; my /= n;
        double sxy = 0, sxx = 0, syy = 0;
        for (int i = 0; i < n; i++) {
            sxy += (x[i] - mx) * (y[i] - my);
            sxx += (x[i] - mx) * (x[i] - mx);
            syy += (y[i] - my) * (y[i] - my);
        }
        return sxy / Math.sqrt(sxx * syy);
    }

    /** league|season -> the real final table, read from the calibration pipeline's joined.csv. */
    private static Map<String, List<Real>> readReal(Path csv) throws IOException {
        List<String> lines = Files.readAllLines(csv);
        String[] header = lines.get(0).split(",");
        int iLg = idx(header, "league"), iSe = idx(header, "season"), iCl = idx(header, "club"),
            iPt = idx(header, "points"), iGf = idx(header, "gf"), iGa = idx(header, "ga");

        Map<String, List<Real>> out = new LinkedHashMap<>();
        for (String line : lines.subList(1, lines.size())) {
            String[] f = splitCsv(line);
            if (f.length <= Math.max(iPt, Math.max(iGf, iGa))) continue;
            out.computeIfAbsent(f[iLg] + "|" + f[iSe], k -> new ArrayList<>())
               .add(new Real(f[iCl], Integer.parseInt(f[iPt]), Integer.parseInt(f[iGf]), Integer.parseInt(f[iGa])));
        }
        return out;
    }

    private static int idx(String[] header, String name) {
        for (int i = 0; i < header.length; i++) if (header[i].trim().equals(name)) return i;
        throw new IllegalStateException("joined.csv has no '" + name + "' column");
    }

    /** Minimal quoted-CSV split — club names can contain commas. */
    private static String[] splitCsv(String line) {
        List<String> out = new ArrayList<>();
        StringBuilder cur = new StringBuilder();
        boolean q = false;
        for (char c : line.toCharArray()) {
            if (c == '"') q = !q;
            else if (c == ',' && !q) { out.add(cur.toString()); cur.setLength(0); }
            else cur.append(c);
        }
        out.add(cur.toString());
        return out.toArray(new String[0]);
    }
}
