package com.draft.footy;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.IntBinaryOperator;

/**
 * Analysis tool (not part of the game): reports the tier distribution per edition under four rating-offset
 * schemes, so we can compare era-normalisation choices. Loads the pool RAW, then re-applies each scheme and
 * recomputes every club's {@link ClubSeason#optimalStrength()} via the real engine. Writes analysis/.
 *
 *   mvn -q compile && java -cp target/classes com.draft.footy.TierReport
 */
public final class TierReport {

    // Mirrors application.properties footy.data.csv. Bare path = multi-edition sofifa export; path:NN = edition NN.
    private static final String[] SPECS = {
        "data/male_players_all.csv", "data/fc_24.csv", "data/fc_25_sofifa.csv:25", "data/EAFC26-Men.csv:26",
        "data/Scraped_data_new/fifa_07.csv:7", "data/Scraped_data_new/fifa_08.csv:8",
        "data/Scraped_data_new/fifa_09.csv:9", "data/Scraped_data_new/fifa_10.csv:10",
        "data/Scraped_data_new/fifa_11.csv:11", "data/Scraped_data_new/fifa_12.csv:12",
        "data/Scraped_data_new/fifa_13.csv:13", "data/Scraped_data_new/fifa_14.csv:14",
    };

    private record Scheme(String name, IntBinaryOperator fn) { }
    private static final String[] TIERS = {"Iconic", "Elite", "Pedigree", "Steady", "Minnow"};

    private static int tierIndex(int s) {
        return s >= 87 ? 0 : s >= 83 ? 1 : s >= 78 ? 2 : s >= 72 ? 3 : 4; // bounds mirror DraftTiers
    }
    private static int editionOf(String season) { // "2008/09" -> 9
        return Integer.parseInt(season.substring(0, 4)) - 1999;
    }

    public static void main(String[] args) throws IOException {
        List<ClubSeason> raw = loadRaw();
        List<Integer> editions = raw.stream().map(c -> editionOf(c.season)).distinct().sorted().toList();

        Scheme[] schemes = {
            new Scheme("Raw sofifa (no offset)", (e, o) -> 0),
            new Scheme("Ceiling-preserving taper (considered, not chosen)", FifaDataLoader::taperOffset),
            new Scheme("Flat +1 (FIFA ≤16)", (e, o) -> e <= 16 ? 1 : 0),
            new Scheme("Flat +2 (FIFA ≤15), +1 (FIFA 16), cap 95 (considered)", (e, o) -> e <= 15 ? 2 : e == 16 ? 1 : 0),
            new Scheme("Low taper: +2≤83, +1@84-85, 0 from 86 (FIFA 16 half)", (e, o) ->
                e >= 17 ? 0 : e == 16 ? (o <= 85 ? 1 : 0) : (o <= 83 ? 2 : o <= 85 ? 1 : 0)),
            new Scheme("Wide taper: +2≤84, +1@85-89, 0 from 90 — COMMITTED (FIFA 16 half)", FifaDataLoader::wideTaperOffset),
        };

        StringBuilder md = new StringBuilder();
        md.append("# Tier distribution by edition — rating-offset schemes\n\n");
        md.append("Generated by `com.draft.footy.TierReport`. Tier = club `optimalStrength` (best-XI overall): ");
        md.append("**Iconic** ≥87 · **Elite** 83–86 · **Pedigree** 78–82 · **Steady** 72–77 · **Minnow** ≤71 ");
        md.append("(mirrors `DraftTiers`). `maxClub` = strongest club-season; `maxOVR` = highest player rating that edition.\n\n");

        StringBuilder csv = new StringBuilder("scheme,season,edition,n,iconic_pct,elite_pct,pedigree_pct,steady_pct,minnow_pct,mean_strength,max_club,max_ovr\n");

        for (Scheme sc : schemes) {
            md.append("## ").append(sc.name()).append("\n\n");
            md.append("| Edition | n | Iconic | Elite | Pedigree | Steady | Minnow | mean | maxClub | maxOVR |\n");
            md.append("|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|\n");

            // adjusted club-seasons (per edition) under this scheme
            Map<Integer, List<Integer>> strengthByEd = new LinkedHashMap<>();
            Map<Integer, Integer> maxOvrByEd = new LinkedHashMap<>();
            int[][] oldMod = new int[2][TIERS.length]; // [0]=old(<=15), [1]=modern(>=16)
            int[] oldModN = new int[2];
            for (ClubSeason cs : raw) {
                int ed = editionOf(cs.season);
                List<Player> adj = new ArrayList<>(cs.roster.size());
                int maxOvr = 0;
                for (Player p : cs.roster) {
                    int o = Math.min(99, p.overall() + sc.fn().applyAsInt(ed, p.overall()));
                    maxOvr = Math.max(maxOvr, o);
                    adj.add(new Player(p.id(), p.name(), p.nation(), p.positions(), o, p.dob()));
                }
                int strength = new ClubSeason(cs.club, cs.season, cs.league, adj).optimalStrength();
                strengthByEd.computeIfAbsent(ed, k -> new ArrayList<>()).add(strength);
                maxOvrByEd.merge(ed, maxOvr, Math::max);
            }

            for (int ed : editions) {
                List<Integer> ss = strengthByEd.getOrDefault(ed, List.of());
                if (ss.isEmpty()) continue;
                int[] tc = new int[TIERS.length];
                int sum = 0, max = 0;
                for (int s : ss) { tc[tierIndex(s)]++; sum += s; max = Math.max(max, s); }
                int grp = ed <= 15 ? 0 : 1;
                for (int i = 0; i < TIERS.length; i++) oldMod[grp][i] += tc[i];
                oldModN[grp] += ss.size();
                double mean = (double) sum / ss.size();
                String season = FifaDataLoader.seasonFor(ed);
                md.append(String.format("| %s | %d | %s | %s | %s | %s | %s | %.1f | %d | %d |\n",
                    season, ss.size(), pct(tc[0], ss.size()), pct(tc[1], ss.size()), pct(tc[2], ss.size()),
                    pct(tc[3], ss.size()), pct(tc[4], ss.size()), mean, max, maxOvrByEd.get(ed)));
                csv.append(String.format("%s,%s,%d,%d,%.1f,%.1f,%.1f,%.1f,%.1f,%.2f,%d,%d%n",
                    csvSafe(sc.name()), season, ed, ss.size(),
                    100.0 * tc[0] / ss.size(), 100.0 * tc[1] / ss.size(), 100.0 * tc[2] / ss.size(),
                    100.0 * tc[3] / ss.size(), 100.0 * tc[4] / ss.size(), mean, max, maxOvrByEd.get(ed)));
            }
            // aggregate rows
            md.append("| **OLD 07–15** | ").append(oldModN[0]).append(" |");
            for (int i = 0; i < TIERS.length; i++) md.append(" **").append(pct(oldMod[0][i], oldModN[0])).append("** |");
            md.append(" — | — | — |\n");
            md.append("| **MODERN 16–26** | ").append(oldModN[1]).append(" |");
            for (int i = 0; i < TIERS.length; i++) md.append(" **").append(pct(oldMod[1][i], oldModN[1])).append("** |");
            md.append(" — | — | — |\n\n");
        }

        Path dir = Path.of("analysis");
        Files.createDirectories(dir);
        Files.writeString(dir.resolve("tier-distribution.md"), md.toString());
        Files.writeString(dir.resolve("tier-distribution.csv"), csv.toString());
        System.out.println("Wrote analysis/tier-distribution.md and .csv  (" + raw.size() + " club-seasons, "
            + editions.size() + " editions)");
    }

    private static String pct(int n, int total) {
        return total == 0 ? "0%" : String.format("%.1f%%", 100.0 * n / total);
    }
    private static String csvSafe(String s) { return s.replace(",", ";"); }

    /** Load the full pool with NO era offset (raw sofifa overalls), deduping by season as DataSeeder does. */
    static List<ClubSeason> loadRaw() throws IOException {
        IntBinaryOperator saved = FifaDataLoader.eraOffsetFn;
        FifaDataLoader.eraOffsetFn = (e, o) -> 0;
        try {
            List<ClubSeason> out = new ArrayList<>();
            Set<String> seenSeasons = new HashSet<>(); // earlier file wins a whole season, exactly like DataSeeder
            for (String spec : SPECS) {
                int colon = spec.lastIndexOf(':');
                int edition = -1;
                Path path = Path.of(spec);
                if (colon > 1) {
                    try { edition = Integer.parseInt(spec.substring(colon + 1).trim()); path = Path.of(spec.substring(0, colon).trim()); }
                    catch (NumberFormatException ignore) { }
                }
                if (!Files.exists(path)) { System.out.println("skip (missing): " + path); continue; }
                List<ClubSeason> part = edition >= 0 ? FifaDataLoader.loadEdition(path, edition)
                                                     : FifaDataLoader.loadAllSeasons(path);
                List<ClubSeason> fresh = part.stream().filter(c -> !seenSeasons.contains(c.season)).toList();
                out.addAll(fresh);
                fresh.forEach(c -> seenSeasons.add(c.season));
            }
            return out;
        } finally {
            FifaDataLoader.eraOffsetFn = saved;
        }
    }
}
